spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
        search-locations: "classpath:/config"
      # search-locations: "file:///Users//eazybytes//Documents//config"
#        git:
#          uri: "https://github.com/anand-chitte/eazybank-config"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true

server:
  port: 8071